config/routes.rb
Rails.application.routes.draw do
  root 'listas#index'
  resources :listas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lista.rb
class Lista < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/listas_controller.rb
class ListasController < ApplicationController
  def index
    @listas = Lista.all
  end

  def new

  end

  def create
    @lista = Lista.new(params.require(:lista).permit(:nome, :descricao))

    @lista.save

    redirect_to lista_path(@lista)
  end

  def show
    @lista = Lista.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listas_helper.rb
module ListasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Projeto Crud With Database" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listas/index.html.erb
<h1>Aqui ficarão as nossas listas</h1>

<table>
    <tr>
        <th>Nome</th>
        <th>Descrição</th>
    </tr>

    <% @listas.each do |lista| %>
        <tr>
            <td><%= lista.nome %></td>
            <td><%= lista.descricao %></td>
        </tr>
    <% end %>
</table>

app/views/listas/new.html.erb
<h1>Criar uma nova lista</h1>
<%= form_with scope: :lista, local: true, url: listas_path do |form| %>
  <p>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </p>
  <p>
    <%= form.label(:descriçao, "Descrição") %>
    <%= form.text_field :descricao %>
  </p>
  <p>
    <%= form.submit("Salvar") %>
  </p>
<% end %>

app/views/listas/show.html.erb
<p>
  <strong>Nome: </strong>
  <%= @lista.nome %>
</p>
<p>
  <strong>Descrição: </strong>
  <%= @lista.descricao %>
</p>